[versions]
junit = "4.13.2"
orgApacheXmlgraphicsBatik = "1.19"
orgApacheXmlgraphicsCommons = "2.11"

[libraries]
junit-junit = { module = "junit:junit", version.ref = "junit" }
org-apache-xmlgraphics-batik-svggen = { module = "org.apache.xmlgraphics:batik-svggen", version.ref = "orgApacheXmlgraphicsBatik" }
org-apache-xmlgraphics-batik-bridge = {module = "org.apache.xmlgraphics:batik-bridge", version.ref = "orgApacheXmlgraphicsBatik"}
org-apache-xmlgraphics-commons = { module = "org.apache.xmlgraphics:xmlgraphics-commons", version.ref = "orgApacheXmlgraphicsCommons" }

[bundles]
org-apache-xmlgraphics =  ["org-apache-xmlgraphics-batik-svggen", "org-apache-xmlgraphics-batik-bridge","org-apache-xmlgraphics-commons"]